#!/bin/bash
# Backup Script for Colloid Surface Chemistry Lab

# Backup Script takes the backup of the database used by the lab.
# Since there is no database being used for Colloid Surface Chemistry Lab, 
# the script does nothing. 

echo "There is no database used for the lab."
